# Generated by Django 3.2.4 on 2021-07-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket1', '0003_auto_20210703_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='Product',
        ),
    ]
