# Generated by Django 3.2.4 on 2021-07-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket1', '0005_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Beer', ' Beer'), ('Pasta/Rice', ' Pasta/Rice'), ('Baking ', ' Baking '), ('Baby Items ', ' Baby Items ')], max_length=200, null=True),
        ),
    ]
